# Tensorflow Loading

In [1]:
import tensorflow as tf
tf.enable_eager_execution()

# 1. Simple Linear Regression 를 TensorFlow 로 구현하기

### Hypothesis

$H(x) = W(x) + b$

In [2]:
x_data = [1,2,3,4,5]
y_data = [1,2,3,4,5]

W = tf.Variable(2.9)
b = tf.Variable(0.5)

# Hypothesis : y = Wx + b
hypothesis = W * x_data + b

### Cost

$cost(W,b) = {1 \over m} \sum_{i=1}^{m}(H(x^{(i)}) - y^{(i)})^2$

In [3]:
cost = tf.reduce_mean(tf.square(hypothesis - y_data))

### tf.reduce_mean()

In [4]:
v = [1., 2., 3., 4.]
tf.reduce_mean(v)   # 2.5

<tf.Tensor: id=31, shape=(), dtype=float32, numpy=2.5>

### tf.square()

In [5]:
tf.square(3)   # 9.0

<tf.Tensor: id=34, shape=(), dtype=int32, numpy=9>

### Gradient Descent 

$minimize\;cost(W,b)$

``` python
A.assign_sub(B)
A = A - B
A -= B
```

In [6]:
# learning_rate
learning_rate = 0.01

# Gradient Descent
with tf.GradientTape() as tape : 
    hypothesis = W * x_data + b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))

W_grad, b_grad = tape.gradient(cost, [W,b])

W.assign_sub(learning_rate * W_grad)
b.assign_sub(learning_rate * b_grad)

print('W = {:.4f}, b = {:.4f}' .format(W.numpy(),b.numpy()))

W = 2.4520, b = 0.3760


###  Parameter Update

In [7]:
W = tf.Variable(2.9)
b = tf.Variable(0.5)

print('{:^5}|{:^10}|{:^10}|{:^10}' .format('i', 'W.numpy()', 'b.numpy()', 'cost'))

for i in range(100) :
    
    with tf.GradientTape() as tape : 
        hypothesis = W * x_data + b
        cost = tf.reduce_mean(tf.square(hypothesis - y_data))
        
    W_grad, b_grad = tape.gradient(cost, [W,b])
    
    W.assign_sub(learning_rate * W_grad)
    b.assign_sub(learning_rate * b_grad)
    
    if i % 10 == 0 : 
        print('{:^5}|{:^10.4}|{:^10.4}|{:^10.6f}' .format(i, W.numpy(), b.numpy(), cost))

  i  |W.numpy() |b.numpy() |   cost   
  0  |  2.452   |  0.376   |45.660004 
 10  |  1.104   | 0.003398 | 0.206336 
 20  |  1.013   | -0.02091 | 0.001026 
 30  |  1.007   | -0.02184 | 0.000093 
 40  |  1.006   | -0.02123 | 0.000083 
 50  |  1.006   | -0.02053 | 0.000077 
 60  |  1.005   | -0.01984 | 0.000072 
 70  |  1.005   | -0.01918 | 0.000067 
 80  |  1.005   | -0.01854 | 0.000063 
 90  |  1.005   | -0.01793 | 0.000059 


### Predict

$H(x) = Wx + b$

In [8]:
print(W * 5.0 + b)
print(W * 3.0 + b)

tf.Tensor(5.0066934, shape=(), dtype=float32)
tf.Tensor(2.9970603, shape=(), dtype=float32)


# 2. Linear Regression and How to minimize cost 를 TensorFlow 로 구현하기

### cost function in pure python

$cost(W) = {1 \over m} \sum_{i=1}^{m}(W(x_{i}) - y_{i})^2$

In [9]:
import numpy as np
X = np.array([1,2,3])
Y = np.array([1,2,3])

def cost_fnc(W,X,Y) : 
    c = 0
    for i in range(len(X)) : 
        c += (W * X[i] - Y[i])**2
    return c / len(X)

for feed_W in np.linspace(-3, 5, num=15) :
    curr_cost = cost_fnc(feed_W, X, Y)
    print("{:6.3f} | {:10.5f}" .format(feed_W, curr_cost))

-3.000 |   74.66667
-2.429 |   54.85714
-1.857 |   38.09524
-1.286 |   24.38095
-0.714 |   13.71429
-0.143 |    6.09524
 0.429 |    1.52381
 1.000 |    0.00000
 1.571 |    1.52381
 2.143 |    6.09524
 2.714 |   13.71429
 3.286 |   24.38095
 3.857 |   38.09524
 4.429 |   54.85714
 5.000 |   74.66667


### cost function in Tensorflow

In [10]:
import numpy as np
X = np.array([1,2,3])
Y = np.array([1,2,3])

def cost_fnc(W,X,Y) : 
    hypothesis = X * W
    return tf.reduce_mean(tf.square(hypothesis - Y))

for feed_W in np.linspace(-3, 5, num=15) :
    curr_cost = cost_fnc(feed_W, X, Y)
    print("{:6.3f} | {:10.5f}" .format(feed_W, curr_cost))

-3.000 |   74.66667
-2.429 |   54.85714
-1.857 |   38.09524
-1.286 |   24.38095
-0.714 |   13.71429
-0.143 |    6.09524
 0.429 |    1.52381
 1.000 |    0.00000
 1.571 |    1.52381
 2.143 |    6.09524
 2.714 |   13.71429
 3.286 |   24.38095
 3.857 |   38.09524
 4.429 |   54.85714
 5.000 |   74.66667


### Gradient Descent

In [11]:
alpha = 0.01
gradient = tf.reduce_mean(tf.multiply(tf.multiply(W,X) - Y, X))
descent = W - tf.multiply(alpha, gradient)
W.assign_sub(descent)

<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=0.00022470951>

In [12]:
# seed
tf.set_random_seed(1234)

# data
x_data = [1., 2., 3., 4.]
y_data = [1., 3., 5., 7.]

# weight
W = tf.Variable(tf.random_normal([1], -100, 100))

# Gradient Descent
for step in range(300) : 
    hypothesis = W * X
    cost = tf.reduce_mean(tf.square(hypothesis - Y))
    
    alpha = 0.01
    gradient = tf.reduce_mean(tf.multiply(tf.multiply(W,X) - Y, X))
    descent = W - tf.multiply(alpha, gradient)
    W.assign_sub(descent)
    
    if step % 10 == 0 : 
        print('{:5}|{:10.4f}|{:10.6f}' .format(step,cost.numpy(),W.numpy()[0]))

    0| 1397.7949| -0.807653
   10|    5.1347| -0.048951
   20|    5.1347| -0.048951
   30|    5.1347| -0.048951
   40|    5.1347| -0.048951
   50|    5.1347| -0.048951
   60|    5.1347| -0.048951
   70|    5.1347| -0.048951
   80|    5.1347| -0.048951
   90|    5.1347| -0.048951
  100|    5.1347| -0.048951
  110|    5.1347| -0.048951
  120|    5.1347| -0.048951
  130|    5.1347| -0.048951
  140|    5.1347| -0.048951
  150|    5.1347| -0.048951
  160|    5.1347| -0.048951
  170|    5.1347| -0.048951
  180|    5.1347| -0.048951
  190|    5.1347| -0.048951
  200|    5.1347| -0.048951
  210|    5.1347| -0.048951
  220|    5.1347| -0.048951
  230|    5.1347| -0.048951
  240|    5.1347| -0.048951
  250|    5.1347| -0.048951
  260|    5.1347| -0.048951
  270|    5.1347| -0.048951
  280|    5.1347| -0.048951
  290|    5.1347| -0.048951


# 3. Multi-variable Linear Regression 를 TensorFlow 로 구현하기

In [13]:
# data and label
x1 = [73., 93., 89., 96., 73]
x2 = [80., 88., 91., 98., 66]
x3 = [75., 93., 90., 100., 70]
Y = [152., 185., 180., 196., 142]

# random weights
w1 = tf.Variable(tf.random_normal([1]))
w2 = tf.Variable(tf.random_normal([1]))
w3 = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))

# learning rate
learning_rate = 0.000001

# Multi-Variable-Linear-Regression
for i in range(1001) : 
    
    # tf.GradientTape() to record the gradient of the cost function
    with tf.GradientTape() as tape : 
        hypothesis = w1*x1 + w2*x2 + w3*x3 + b
        cost = tf.reduce_mean(tf.square(hypothesis - Y))
    # calculates the gradients of the cost
    w1_grad, w2_grad, w3_grad, b_grad = tape.gradient(cost, [w1,w2,w3,b])
    
    # update w1,w2,w3 and b
    w1.assign_sub(learning_rate * w1_grad)
    w2.assign_sub(learning_rate * w2_grad)
    w3.assign_sub(learning_rate * w3_grad)
    b.assign_sub(learning_rate * b_grad)
    
    # process print
    if i % 50 == 0 : 
        print("{:5} | {:12.4f}" .format(i,cost.numpy()))

    0 |     551.4631
   50 |       9.5045
  100 |       3.4850
  150 |       3.4123
  200 |       3.4056
  250 |       3.3996
  300 |       3.3936
  350 |       3.3877
  400 |       3.3818
  450 |       3.3759
  500 |       3.3700
  550 |       3.3641
  600 |       3.3582
  650 |       3.3523
  700 |       3.3465
  750 |       3.3406
  800 |       3.3347
  850 |       3.3290
  900 |       3.3232
  950 |       3.3175
 1000 |       3.3117


### Matrix

$H(X) = XW$

In [14]:
data = np.array([[73.,  80.,  75.,  152.],
                 [93.,  88.,  93.,  185.],
                 [89.,  91.,  90.,  180.],
                 [96.,  98., 100.,  196.],
                 [73.,  66.,  70.,  142.]], dtype=np.float32)

# slice data
X = data[:, :-1]
print('X','\n',X,'\n')
y = data[:, [-1]]
print('y','\n',y,'\n')

W = tf.Variable(tf.random_normal([3,1]))
print('W','\n',W.numpy(),'\n')
b = tf.Variable(tf.random_normal([1]))
print('b','\n',b.numpy(),'\n')

def predict(X) :
    return tf.matmul(X,W) + b

X 
 [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]] 

y 
 [[152.]
 [185.]
 [180.]
 [196.]
 [142.]] 

W 
 [[-0.3198804 ]
 [ 1.3575249 ]
 [-0.15776916]] 

b 
 [0.80348307] 

